"""baseline schema

Revision ID: 612481f0ad55
Revises: 
Create Date: 2026-05-06 15:21:21.825363

This migration captures the schema as it exists at the start of Phase 0.
Existing production databases were created via ``Base.metadata.create_all``
plus the hand-written ``ensure_schema_compatibility`` block in ``main.py``.
For those DBs, run::

    TASK_CENTER_DATABASE_PATH=/path/to/data/task_center.db \
        .venv/bin/alembic stamp head

ONCE per database to mark them as already at this revision without
re-running the migration. Future schema changes go through new Alembic
revisions.
"""
from collections.abc import Sequence

import sqlalchemy as sa

import models  # custom column types like UTCDateTimeText live here
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '612481f0ad55'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_order_json', sa.Text(), nullable=False),
    sa.Column('pinned_projects_json', sa.Text(), nullable=False),
    sa.Column('project_order_json', sa.Text(), nullable=False),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('updated_at', models.UTCDateTimeText(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_preferences_id'), ['id'], unique=False)

    op.create_table('knowledge_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pinned_customer_ids_json', sa.Text(), nullable=False),
    sa.Column('customer_order_ids_json', sa.Text(), nullable=False),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('updated_at', models.UTCDateTimeText(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_preferences_id'), ['id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('aliases_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('updated_at', models.UTCDateTimeText(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_status'), ['status'], unique=False)

    op.create_table('review_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('period_start', models.UTCDateTimeText(), nullable=True),
    sa.Column('period_end', models.UTCDateTimeText(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('material_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('updated_at', models.UTCDateTimeText(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_batches_batch_type'), ['batch_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_batches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_batches_status'), ['status'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('project_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('start_at', models.UTCDateTimeText(), nullable=True),
    sa.Column('target_end_at', models.UTCDateTimeText(), nullable=True),
    sa.Column('actual_end_at', models.UTCDateTimeText(), nullable=True),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('updated_at', models.UTCDateTimeText(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', models.UTCDateTimeText(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('updated_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('completed_at', models.UTCDateTimeText(), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('canceled_at', models.UTCDateTimeText(), nullable=True),
    sa.Column('deferred_to', models.UTCDateTimeText(), nullable=True),
    sa.Column('nightly_bucket', sa.String(length=32), nullable=True),
    sa.Column('nightly_reviewed_at', models.UTCDateTimeText(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project'), ['project'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('customer_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_refs_json', sa.Text(), nullable=False),
    sa.Column('value_types_json', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', models.UTCDateTimeText(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('material_date', models.UTCDateTimeText(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('project_v2_id', sa.Integer(), nullable=True),
    sa.Column('review_batch_id', sa.Integer(), nullable=True),
    sa.Column('material_type', sa.String(length=32), nullable=False),
    sa.Column('period_start', models.UTCDateTimeText(), nullable=True),
    sa.Column('period_end', models.UTCDateTimeText(), nullable=True),
    sa.Column('raw_facts_markdown', sa.Text(), nullable=True),
    sa.Column('generation_meta_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('updated_at', models.UTCDateTimeText(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_v2_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_batch_id'], ['review_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_materials_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_materials_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_materials_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_materials_material_date'), ['material_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_materials_project'), ['project'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_materials_project_v2_id'), ['project_v2_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_materials_review_batch_id'), ['review_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_materials_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_materials_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_materials_task_id'), ['task_id'], unique=False)

    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('fact_date', models.UTCDateTimeText(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_markdown', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('value_types_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('updated_at', models.UTCDateTimeText(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_fact_date'), ['fact_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_task_id'), ['task_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('remind_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('updated_at', models.UTCDateTimeText(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_remind_at'), ['remind_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_task_id'), ['task_id'], unique=False)

    op.create_table('task_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_events_task_id'), ['task_id'], unique=False)

    op.create_table('task_recurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('time_of_day', sa.String(length=16), nullable=True),
    sa.Column('days_of_week_json', sa.Text(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('start_at', models.UTCDateTimeText(), nullable=True),
    sa.Column('end_at', models.UTCDateTimeText(), nullable=True),
    sa.Column('next_run_at', models.UTCDateTimeText(), nullable=True),
    sa.Column('last_run_at', models.UTCDateTimeText(), nullable=True),
    sa.Column('reminder_offsets_json', sa.Text(), nullable=False),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.Column('updated_at', models.UTCDateTimeText(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_recurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_recurrences_frequency'), ['frequency'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_recurrences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_recurrences_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_recurrences_task_id'), ['task_id'], unique=True)

    op.create_table('customer_material_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', models.UTCDateTimeText(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['customer_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_material_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_material_facts_fact_id'), ['fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_material_facts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_material_facts_material_id'), ['material_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_material_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_material_facts_material_id'))
        batch_op.drop_index(batch_op.f('ix_customer_material_facts_id'))
        batch_op.drop_index(batch_op.f('ix_customer_material_facts_fact_id'))

    op.drop_table('customer_material_facts')
    with op.batch_alter_table('task_recurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_recurrences_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_recurrences_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_task_recurrences_id'))
        batch_op.drop_index(batch_op.f('ix_task_recurrences_frequency'))

    op.drop_table('task_recurrences')
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_events_id'))
        batch_op.drop_index(batch_op.f('ix_task_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_task_events_created_at'))

    op.drop_table('task_events')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_task_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_reminders_remind_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_task_id'))
        batch_op.drop_index(batch_op.f('ix_facts_status'))
        batch_op.drop_index(batch_op.f('ix_facts_source_type'))
        batch_op.drop_index(batch_op.f('ix_facts_project_id'))
        batch_op.drop_index(batch_op.f('ix_facts_id'))
        batch_op.drop_index(batch_op.f('ix_facts_fact_date'))
        batch_op.drop_index(batch_op.f('ix_facts_customer_id'))

    op.drop_table('facts')
    with op.batch_alter_table('customer_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_materials_task_id'))
        batch_op.drop_index(batch_op.f('ix_customer_materials_status'))
        batch_op.drop_index(batch_op.f('ix_customer_materials_source_type'))
        batch_op.drop_index(batch_op.f('ix_customer_materials_review_batch_id'))
        batch_op.drop_index(batch_op.f('ix_customer_materials_project_v2_id'))
        batch_op.drop_index(batch_op.f('ix_customer_materials_project'))
        batch_op.drop_index(batch_op.f('ix_customer_materials_material_date'))
        batch_op.drop_index(batch_op.f('ix_customer_materials_id'))
        batch_op.drop_index(batch_op.f('ix_customer_materials_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_materials_archived_at'))

    op.drop_table('customer_materials')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_source_type'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_project'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_customer_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.drop_index(batch_op.f('ix_projects_customer_id'))

    op.drop_table('projects')
    with op.batch_alter_table('review_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_batches_status'))
        batch_op.drop_index(batch_op.f('ix_review_batches_id'))
        batch_op.drop_index(batch_op.f('ix_review_batches_batch_type'))

    op.drop_table('review_batches')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_status'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))

    op.drop_table('customers')
    with op.batch_alter_table('board_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_preferences_id'))

    op.drop_table('board_preferences')
    with op.batch_alter_table('knowledge_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_preferences_id'))

    op.drop_table('knowledge_preferences')
    # ### end Alembic commands ###
